
spring:
  datasource:
    name: bogeshare
    url: jdbc:mysql://localhost:3306/bogeshare?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: GC.LJS0217
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: classpath:/static/pages/
      suffix: .html
  thymeleaf:
    cache: true
    prefix: classpath:/static/pages/
    suffix: .html

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test.bean
server:
  port: 8001